### ISSUE TITLE
how to compile it for android?

### ISSUE THREAD

**Issue by frannnnnk** [ivanarh/libunwind-ndk#1]
hi, very glad to see this project.I need to compile libunwind into my shared library, but i dont know how to compile it,can you tell me ? thanks.

**Comment by ivanarh** [comment]
See https://github.com/ivanarh/nativecrashes/tree/libunwind
Don't forget:
`git submodule update --init --recursive`

**Comment by frannnnnk** [comment]
It is very detailed, thank you so much!

**Comment by frannnnnk** [comment]
libunwind and libunwindstack,which one do you recommend?
I think libunwindstack works better than libunwind, but it's a little large.

**Comment by ivanarh** [comment]
I recommend libunwindstack for C++11 projects and libunwind for plain C and old C++ projects.
The reason why libunwindstack may seem larger is necessity of standard C++ library static linking. But if you already use C++11 it isn't a problem.
Also can may optimize both libraries by removing unused code. For example, you can purge DWARF unwinding code because it's useless on devices.
